// <auto-generated />
namespace TravelProject1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_Authencation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_Authencation));
        
        string IMigrationMetadata.Id
        {
            get { return "202010240756536_update_Authencation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
